### ISSUE TITLE
The output of A direct running of eg1_cat_and_wolf.m seems bad.

### ISSUE THREAD

**Issue by wlsdzyzl** [llorz/SGA19_zoomOut#3]
![image](https://user-images.githubusercontent.com/26569279/105709494-c14cf280-5f50-11eb-8898-2cab93a45a9d.png)

**Comment by llorz** [comment]
can you please check this first "https://github.com/llorz/SGA19_zoomOut/issues/1" to see if it solves your problem? Basically, it's just because the initial guess should be changed (since your computed LB can be different from mine in different pc). 

Please do let  me know if you have further questions.

**Comment by wlsdzyzl** [comment]
> can you please check this first "#1" to see if it solves your problem? Basically, it's just because the initial guess should be changed (since your computed LB can be different from mine in different pc).
> 
> Please do let me know if you have further questions.

Cool, sorry that i didn't check the previous issue. That was exactly what i just experienced! Anyway, i think maybe it's better to add some codes to automatically check and flip the initial guess. Thank you!
